config/routes.rb
DynamicPortal::Application.routes.draw do

  root to: 'welcome#index'

  match 'auth/:provider/callback', to: 'integrations#create', via: [:get]
  match 'auth/failure', to: redirect('/'), via: [:get]

  match '/portal' => 'portal#index', :as => :portal_index, via: [:get]
  match '/set_localization/(:locale)' => 'portal#set_localization', as: :set_localization, via: [:post]
  match '/logout' => 'portal#logout', :as => :logout, via: [:get]

  resources :password_restore

  resources :welcome do
    collection do
      get :about
      post :do_login
      get :forgot
      get 'activate/(:token)' => 'welcome#activate', as: :activate
    end
  end

  resources :api do
    collection do
      get :get_user, :defaults => { :format => 'json' }
    end
  end

  namespace :portal do

    match 'dashboard' => 'dashboard#index', as: :dashboard_index, via: [:get]
    namespace :dashboard do

      resources :posts do
        resources :comments
      end

      resources :messages

      resources :events
    end

    resources :friendships do
      collection do
        post 'create/(:friend_id)' => 'friendships#create', as: :create
      end
    end

    resources :users

    resources :games

  end
end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user, foreign_key: :author_id

end

app/controllers/portal/dashboard/events_controller.rb
class Portal::Dashboard::EventsController < PortalController
end

app/controllers/portal/dashboard/messages_controller.rb
class Portal::Dashboard::MessagesController < PortalController
  before_filter :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to portal_message_path(@message), notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to portal_message_path(@message), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to portal_messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :author_id, :receiver_id)
    end
end

app/controllers/portal/dashboard/posts_controller.rb
class Portal::Dashboard::PostsController < PortalController
  before_filter :set_post, only: [:show, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post].merge!({author_id: current_user.id}))

    respond_to do |format|
      if @post.save
        format.html { redirect_to_with_notice portal_dashboard_index_path(@post), t('notices.dashboard.news.post_created'), :succeess }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { redirect_to_with_notice portal_dashboard_index_path(tab: 'news'), t('globals.error') }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to_with_notice portal_dashboard_index_path, t('notices.dashboard.news.post_deleted') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

end

app/controllers/portal/dashboard_controller.rb
class Portal::DashboardController < PortalController

  def index
    type = params[:what]
    @post = Post.new
    @posts = Post.newly_added if type == 'new'
    @posts = Post.unanswered if type == 'unanswered'
    @posts = Post.hot if type == 'hot'
    @posts = Post.my(current_user.id) if type == 'my'

    @posts ||= Post.all
  end

end

app/helpers/portal/dashboard/events_helper.rb
module Portal::Dashboard::EventsHelper
end

app/helpers/portal/dashboard/messages_helper.rb
module Portal::Dashboard::MessagesHelper
end

app/helpers/portal/dashboard/posts_helper.rb
module Portal::Dashboard::PostsHelper

  def posted_at(post)
    'created ' + time_ago_in_words(post.created_at) + ' ago'
  end

end

app/views/portal/dashboard/messages/_form.html.haml
= form_for @message, url: portal_dashboard_message_path(@message) do |f|
  - if @message.errors.any?
    %div#error_explanation"
      %h2
        = pluralize(@message.errors.count, "error")
        prohibited this message from being saved:
      %ul
      - @message.errors.full_messages.each do |msg|
        %li
          = msg

  %div.field
    = f.label :content
    %br
    = f.text_area :content
  %div.field
    = f.label :author_id
    %br
    = f.number_field :author_id
  %div.field
    = f.label :receiver_id
    %br
    = f.number_field :receiver_id

  %div.actions
    = f.submit

app/views/portal/dashboard/messages/edit.html.haml
%h1
  Editing message

= render 'form'

= link_to 'Show', @message
|
= link_to 'Back', portal_dashboard_messages_path

app/views/portal/dashboard/messages/index.html.haml
%h1
  Listing messages

%table
  %thead
    %tr
      %th
        Content
      %th
        Author
      %th
        Receiver
      %th
      %th
      %th

  %tbody
    - @messages.each do |message|
      %tr
        %td
          = message.content
        %td
          = message.author_id
        %td
          = message.receiver_id
        %td
          = link_to 'Show', message
        %td
          = link_to 'Edit', edit_portal_dashboard_message_path(message)
        %td
          = link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Message', new_portal_dashboard_message_path

app/views/portal/dashboard/messages/new.html.haml
%h1
  New message

= render 'form'

= link_to 'Back', portal_dashboard_messages_path

app/views/portal/dashboard/messages/show.html.haml
%p#notice
  = notice

%p
  %strong
    Content:
  = @message.content

%p
  %strong
    Author:
  = @message.author_id

%p
  %strong
    Receiver:
  = @message.receiver_id

= link_to 'Edit', edit_portal_dashboard_message_path(@message)
|
= link_to 'Back', portal_dashboard_messages_path