config/routes.rb
DynamicPortal::Application.routes.draw do

  root to: 'welcome#index'

  match 'auth/:provider/callback', to: 'integrations#create', via: [:get]
  match 'auth/failure', to: redirect('/'), via: [:get]

  match '/portal' => 'portal#index', :as => :portal_index, via: [:get]
  match '/set_localization/(:locale)' => 'portal#set_localization', as: :set_localization, via: [:post]
  match '/logout' => 'portal#logout', :as => :logout, via: [:get]

  resources :password_restore

  resources :welcome do
    collection do
      get :about
      post :do_login
      get :forgot
      get 'activate/(:token)' => 'welcome#activate', as: :activate
    end
  end

  resources :api do
    collection do
      get :get_user, :defaults => { :format => 'json' }
    end
  end

  namespace :portal do

    match 'dashboard' => 'dashboard#index', as: :dashboard_index, via: [:get]
    namespace :dashboard do

      resources :posts do
        resources :comments
      end

      resources :messages

      resources :events
    end

    resources :friendships do
      collection do
        post 'create/(:friend_id)' => 'friendships#create', as: :create
      end
    end

    resources :users

    resources :games

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  include LoginExt
  include ApplicationHelper

  def index
    @source = params[:source] if params[:source]
    make_auto_log_in if in_social_box?
    redirect_if_logged_in
    @user = User.new
  end

  def activate
    @user = User.find_by_remember_me_token params[:token] if params[:token]
    if @user && !@user.active?
      @user.activate_account!
      redirect_to_with_notice root_path, t('notices.registration.activation_success'), :success
    elsif @user && @user.active?
      redirect_to_with_notice root_path, t('notices.registration.account_activated')
    end
    redirect_to_with_notice root_path, t('notices.registration.account_activation_failed'), :error
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_login.html.haml
- unless in_social_box?
  .social-login
    = t('welcome.log_in_with')
    = link_to image_tag('Facebook_login_40x40.png'), '/auth/facebook', id: 'sign_in'
    = link_to image_tag('vkontakte_login_40x40.png'), '/auth/vkontakte', id: 'sign_in'
    = link_to image_tag('Twitter_login_40x40.png'), '/auth/twitter', id: 'sign_in'
.social-warning
  %i.icon-warning-sign
  = t('welcome.social_login_warning')
.login-form
  = form_tag(do_login_welcome_index_url) do
    = hidden_field_tag :source, s
    = text_field_tag :email, nil, :placeholder => 'Email'
    = password_field_tag :password, nil, :placeholder => 'Password'

    = submit_tag t('welcome.login.sign_in'), :class => 'btn btn-small btn-primary'
    = link_to t('welcome.login.register'), '#registerModal', :class => 'btn btn-small btn-success', 'data-toggle'=>'modal'

    %div.remember-me
      = check_box_tag :remember_me, 1, params[:remember_me]
      %div.small-text
        = t('welcome.login.remember_me')
    = link_to t('welcome.login.forgot'), '#restorePasswdModal', 'data-toggle'=>'modal'

= render :partial => 'register_modal'
= render partial: 'password_restore/new_modal'

app/views/welcome/_register_modal.html.haml
%div{class:'modal hide fade', id:'registerModal', tabindex:'-1', role:'dialog', 'aria-hidden'=>'true'}
  .modal-header
    %button{type:'button', class:'close', 'data-dismiss'=>'modal', 'aria-hidden'=>'true'}
      ×
    .modal-hd
      = t('welcome.registration.register_form')
    .modal-desc
      = t('welcome.registration.fill_in_fields')
  .modal-body
    = simple_form_for [:portal, @user], validate: true, method: :post, html:{ class:'form-horizontal'} do |form|
      = form.input :email
      = form.input :first_name
      = form.input :last_name, hint: 'No special characters, please!'
      = form.input :password
      = form.input :confirm_password
      .captcha
        = recaptcha_tags( display: {theme: 'clean', custom_theme_widget: 'recaptcha_widget'})
      .modal-footer
        <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">
        %i.icon-remove
        = t('global.close')
        </button>
        = form.button :submit, class: 'btn btn-small btn-success'

app/views/welcome/index.html.haml
.heading
  = t('welcome.title')
.subheading
  = t('welcome.description')

= render partial: 'login', locals: {s: @source} unless current_user