config/routes.rb
DynamicPortal::Application.routes.draw do

  root to: 'welcome#index'

  match 'auth/:provider/callback', to: 'integrations#create', via: [:get]
  match 'auth/failure', to: redirect('/'), via: [:get]

  match '/portal' => 'portal#index', :as => :portal_index, via: [:get]
  match '/set_localization/(:locale)' => 'portal#set_localization', as: :set_localization, via: [:post]
  match '/logout' => 'portal#logout', :as => :logout, via: [:get]

  resources :password_restore

  resources :welcome do
    collection do
      get :about
      post :do_login
      get :forgot
      get 'activate/(:token)' => 'welcome#activate', as: :activate
    end
  end

  resources :api do
    collection do
      get :get_user, :defaults => { :format => 'json' }
    end
  end

  namespace :portal do

    match 'dashboard' => 'dashboard#index', as: :dashboard_index, via: [:get]
    namespace :dashboard do

      resources :posts do
        resources :comments
      end

      resources :messages

      resources :events
    end

    resources :friendships do
      collection do
        post 'create/(:friend_id)' => 'friendships#create', as: :create
      end
    end

    resources :users

    resources :games

  end
end

app/views/navigation/_dashboard_dropdown.html.haml
%ul.nav
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-list
      = t('navigation.header.dashboard')
      %b.caret
    %ul.dropdown-menu
      %li
        = link_to t('dashboard.news.header'), portal_dashboard_index_path(tab: 'news')
      %li
        = link_to t('dashboard.forum.header'), portal_dashboard_index_path(tab: 'forum')
      %li
        = link_to t('dashboard.events.header'), portal_dashboard_index_path(tab: 'events')

app/views/navigation/_flash.html.haml
- if flash[:notice]
  %p{:class => 'alert alert-info', id: 'flash-info'}
    = flash[:notice]
-if flash[:error]
  %p{:class => 'alert alert-error', id: 'flash-error'}
    = flash[:error]
-if flash[:success]
  %p{:class => 'alert alert-success', id: 'flash-success'}
    = flash[:success]

app/views/navigation/_footer,html.haml
#footer
  = copyright_notice_year_range(2010)
  = link_to 'Dynamic Games Inc.', 'http://immense-gorge-7833.herokuapp.com/'
    All Rights Reserved.

app/views/navigation/_games_dropdown.html.haml
%ul.nav
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-leaf
      = t('navigation.header.games')
      %b.caret
    %ul.dropdown-menu
      %li
        = link_to t('games.globals.browse_all'), portal_games_path
      %li
        = link_to t('games.types.board.chess'), 'http://www.google.com/search', target: '_blank'
      %li
        = link_to t('games.types.card.poker'), 'http://www.vk.com', target: '_blank'

app/views/navigation/_profile_dropdown.html.haml
%ul{class:'nav pull-right'}
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-home
      = current_user.first_name
      %b.caret
    %ul.dropdown-menu
      %li
        = link_to t('globals.home'), portal_user_path(current_user.id)
      %li
        = link_to(t('globals.edit'), edit_portal_user_path(current_user.id))
      - unless in_social_box?
        %li.divider
        %li.log-out
          = button_to t('globals.sign_out'), logout_path, method: :get, class: 'btn btn-danger'

app/views/navigation/_users_dropdown.html.haml
%ul.nav
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-user
      = t('navigation.header.users')
      %b.caret
    %ul.dropdown-menu
      %li
        = link_to t('users.header.online'), portal_users_path(list: :online)
      %li
        = link_to t('users.header.friends'), portal_users_path(list: :friends)
      %li
        = link_to t('users.header.all'), portal_users_path

app/views/navigation/header.html.haml
%div{class: 'navbar navbar-inverse navbar-fixed-top'}
  %div.navbar-inner
    %div.container
      %a{class:'btn btn-navbar', 'data-toggle'=>'collapse', 'data-target'=>'.nav-collapse'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a{class:'brand', href:'#'}
        = t('globals.dynamic_games')
      %div.nav-collapse
        - if current_user.present?
          = render partial: 'navigation/dashboard_dropdown'
          = render partial: 'navigation/users_dropdown'
          = render partial: 'navigation/games_dropdown'
          = render partial: 'navigation/profile_dropdown'